/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
//import Business.WorkQueue.HodApprovalWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Priyank
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private ManagerOrganization managerOrganization;
    
    public ManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,
            EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.managerOrganization = (ManagerOrganization)organization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        model.setRowCount(0);
        System.out.println(""+userAccount);
        System.out.println(""+userAccount.getRole());
        System.out.println(""+userAccount.getWorkQueue().getWorkRequestList());
        
        
//        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
//                ManagerApprovalWorkRequest req = (ManagerApprovalWorkRequest) request;
//                System.out.println("My received is :"+req.getReceiver());
//                System.out.println("Useraccount used is "+userAccount);
//                System.out.println("My request status is :"+req.getStatus());
////                
////                if (req.getReceiver() == userAccount & req.getStatus().equals("Pending with Manager")) {
////                    System.out.println("Manager populate table inside if");
////                    Object[] row = new Object[3];
////                    row[0] = request;
////                    row[1] = req.getNgoEventReq().getDate();
////                    row[2] = req.getNgoEventReq().getDuration();
////                    model.addRow(row);
//////                }
//        }

           for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(organization instanceof EmployeeOrganization){
                        //System.out.println(""+organization.getWorkQueue().getWorkRequestList());
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request instanceof ManagerApprovalWorkRequest){
                                ManagerApprovalWorkRequest req = (ManagerApprovalWorkRequest)request;
                                if(request.getReceiver() == userAccount & request.getStatus().equals("Pending with Manager")){
                                    Object[] row = new Object[3];
                                    row[0] = request;
                                    row[1] = req.getNgoEventReq().getDate();
                                    row[2] = req.getNgoEventReq().getDuration();
                                    model.addRow(row);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        approvedJButton = new javax.swing.JButton();
        rejectedJButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ManagerRole/volunteer.png"))); // NOI18N
        jLabel1.setText("Team Volunteering Activity Request");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        refreshJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refreshJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ManagerRole/refresh.png"))); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refreshJButton.setBorderPainted(false);
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 130, 50));

        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Event Date", "Event Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, 137));

        approvedJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        approvedJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ManagerRole/accept.png"))); // NOI18N
        approvedJButton.setText("Approve");
        approvedJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        approvedJButton.setBorderPainted(false);
        approvedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvedJButtonActionPerformed(evt);
            }
        });
        add(approvedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 120, 50));

        rejectedJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rejectedJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ManagerRole/reject.png"))); // NOI18N
        rejectedJButton.setText("Reject");
        rejectedJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rejectedJButton.setBorderPainted(false);
        rejectedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectedJButtonActionPerformed(evt);
            }
        });
        add(rejectedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 130, 50));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();        //        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void approvedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvedJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        ManagerApprovalWorkRequest request = (ManagerApprovalWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        EducationEventWorkRequest ngoEventReq = request.getNgoEventReq();
        if(ngoEventReq.getEmployeeList().size() < Integer.parseInt(ngoEventReq.getInstructorRequired())){
            request.setStatus("Registered");
            UserAccount senderOfrequest = request.getSender();
            Employee senderEmp = senderOfrequest.getEmployee();
            ngoEventReq.getEmployeeList().add(senderEmp);
            senderOfrequest.getWorkQueue().getWorkRequestList().add(ngoEventReq);;
        }
        else{
            request.setStatus("Waitlisted");
            UserAccount senderOfrequest = request.getSender();
            Employee senderEmp = senderOfrequest.getEmployee();
            ngoEventReq.getEmployeeWaitList().add(senderEmp);
        }

        JOptionPane.showMessageDialog(null, "Approved!");
        populateTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_approvedJButtonActionPerformed

    private void rejectedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectedJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        //HodApprovalWorkRequest request = (HodApprovalWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        //
        //request.setStatus("Rejected");

        ManagerApprovalWorkRequest request = (ManagerApprovalWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        EducationEventWorkRequest ngoEventReq = request.getNgoEventReq();
        if(ngoEventReq.getEmployeeList().size() < Integer.parseInt(ngoEventReq.getInstructorRequired())){
            request.setStatus("Rejected");
            UserAccount senderOfrequest = request.getSender();
            Employee senderEmp = senderOfrequest.getEmployee();
            ngoEventReq.getEmployeeList().add(senderEmp);
            senderOfrequest.getWorkQueue().getWorkRequestList().add(ngoEventReq);;
        }
        JOptionPane.showMessageDialog(null, "Rejected!");

        populateTable();
        //
        //        EmployeeEventRegistrationJPanel empEventRegistrationJPanel = new EmployeeEventRegistrationJPanel(userProcessContainer, request);
        //        userProcessContainer.add("empEventRegistrationJPanel", empEventRegistrationJPanel);
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);
    }//GEN-LAST:event_rejectedJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton approvedJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton rejectedJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
