/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmployeeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EmployeeOrganization;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class EmployeeEventRegistrationJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    EducationEventWorkRequest request;
    UserAccount account;
    Organization organization;
    EcoSystem business;

    public EmployeeEventRegistrationJPanel(JPanel userProcessContainer, EducationEventWorkRequest request, UserAccount account,Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account=account;
        this.organization=(EmployeeOrganization)organization;
        this.business = business;
        instructorsRequiredTextBox.setText(request.getInstructorRequired());
        dateTextBox.setText(request.getDate());
        venueTextBox.setText(request.getDate());
        ngoTextBox.setText(request.getNgoName());
        workshopNameTextBox.setText(request.getWorkshopName());
        subjectTextBox.setText(request.getTopics());
        eventTextBox.setText(request.getDuration());
        commentsTextBox.setText(request.getComments());
        registerEnabled();
    }
    
    public void registerEnabled(){
        try
        {
        for(WorkRequest req: organization.getWorkQueue().getWorkRequestList()){
            if(req instanceof ManagerApprovalWorkRequest){
                ManagerApprovalWorkRequest managerReq = (ManagerApprovalWorkRequest)req;
                if(managerReq.getNgoEventReq()==request){
                if(!(managerReq.getSender()==account)){
                    Register.setEnabled(true);
                }
                else
                    Register.setEnabled(false);
            }
        }
        }}
        catch(Exception e){
            Register.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTextBox = new javax.swing.JTextField();
        commentsTextBox = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        ngoTextBox = new javax.swing.JTextField();
        instructorsRequiredTextBox = new javax.swing.JTextField();
        dateTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        venueTextBox = new javax.swing.JTextField();
        subjectTextBox = new javax.swing.JTextField();
        workshopNameTextBox = new javax.swing.JTextField();
        backJButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventTextBox.setEditable(false);
        eventTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(eventTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 240, 30));

        commentsTextBox.setEditable(false);
        commentsTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentsTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsTextBoxActionPerformed(evt);
            }
        });
        add(commentsTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 240, 30));

        Register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/EmployeeRole/reg.png"))); // NOI18N
        Register.setText("Register");
        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.setBorderPainted(false);
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 750, 110, 40));

        ngoTextBox.setEditable(false);
        ngoTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(ngoTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 240, 30));

        instructorsRequiredTextBox.setEditable(false);
        instructorsRequiredTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructorsRequiredTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorsRequiredTextBoxActionPerformed(evt);
            }
        });
        add(instructorsRequiredTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 240, 30));

        dateTextBox.setEditable(false);
        dateTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(dateTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 240, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/EmployeeRole/workshop.png"))); // NOI18N
        jLabel1.setText("Education Workshop Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        venueTextBox.setEditable(false);
        venueTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(venueTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 240, 30));

        subjectTextBox.setEditable(false);
        subjectTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(subjectTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 240, 30));

        workshopNameTextBox.setEditable(false);
        workshopNameTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(workshopNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 240, 30));

        backJButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/EmployeeRole/back.png"))); // NOI18N
        backJButton4.setText("Back");
        backJButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton4.setBorderPainted(false);
        backJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton4ActionPerformed(evt);
            }
        });
        add(backJButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 750, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/work.png"))); // NOI18N
        jLabel10.setText("Workshop Name:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/teaching.png"))); // NOI18N
        jLabel3.setText("Instructors required :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 180, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel11.setText("Date of Event :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 140, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel4.setText("Venue :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 90, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/topics.png"))); // NOI18N
        jLabel12.setText("Topics :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel6.setText("Duration :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/hospital/comments.png"))); // NOI18N
        jLabel8.setText("Comments :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void commentsTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentsTextBoxActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed

        String date = dateTextBox.getText();
        
        ManagerApprovalWorkRequest managerRequest = new ManagerApprovalWorkRequest();
        managerRequest.setDate(date);
        managerRequest.setSender(account);
        managerRequest.setStatus("Pending with Manager");
        managerRequest.setNgoEventReq(request);
        
        
        System.out.println("Send account is "+account);
        System.out.println("Employee for the account is "+account.getEmployee());
        System.out.println("Employees manager is: "+account.getEmployee().getManagerId());
        
        for(Network network : business.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof ManagerOrganization)
                    {
                        System.out.println("My manager is: "+account.getEmployee().getManagerId());
                        managerRequest.setReceiver(organization.getUserAccountDirectory().getUserAccount(account.getEmployee().getManagerId()));
                        
                    }
                }
            }
        }

        System.out.println("Message received is :"+managerRequest.getReceiver());
        System.out.println("Manager request created is: :"+managerRequest.getMessage());
        
        organization.getWorkQueue().getWorkRequestList().add(managerRequest);
        System.out.println("Checking the workrequest list created"+organization.getWorkQueue().getWorkRequestList());
        
        account.getWorkQueue().getWorkRequestList().add(managerRequest);
        System.out.println(""+account.getWorkQueue().getWorkRequestList());
        
        JOptionPane.showMessageDialog(null, "Registration Approval Request Sent to Manager");
        Register.setEnabled(false);
        //            System.out.println(organization.getWorkQueue().getWorkRequestList());

        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterActionPerformed

    private void instructorsRequiredTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorsRequiredTextBoxActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_instructorsRequiredTextBoxActionPerformed

    private void backJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton4ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] comps = userProcessContainer.getComponents();
        for(Component c: comps) {
            if(c instanceof EmployeeWorkAreaJPanel) {
                EmployeeWorkAreaJPanel panel = (EmployeeWorkAreaJPanel) c;
                panel.populateTable();
                panel.populateEventRegistrationStatusTable();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Register;
    private javax.swing.JButton backJButton4;
    private javax.swing.JTextField commentsTextBox;
    private javax.swing.JTextField dateTextBox;
    private javax.swing.JTextField eventTextBox;
    private javax.swing.JTextField instructorsRequiredTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JTextField subjectTextBox;
    private javax.swing.JTextField venueTextBox;
    private javax.swing.JTextField workshopNameTextBox;
    // End of variables declaration//GEN-END:variables
}
