/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GroceryRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GroceryAdminOrganization;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.GroceryRole;
import Business.Role.NGORole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GroceryDistributionEventRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.NGORole.NGOWorkAreaJPanel;

/**
 *
 * @author Apoorva
 */
public class RequestGroceryDistributionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private Organization organization;
    private List<Items> itemList = new ArrayList();
    private OrganizationDirectory organizationDir;

    public RequestGroceryDistributionJPanel(JPanel userProcessContainer, UserAccount account, GroceryAdminOrganization groceryStoreOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = groceryStoreOrganization;
        this.business = business;
        this.organizationDir = enterprise.getOrganizationDirectory();
        populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        submitRequest = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        messageText = new javax.swing.JTextField();
        ngoNameComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        itemQtyTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        deleteItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        itemNameTxt = new javax.swing.JTextField();
        eventDate = new org.jdesktop.swingx.JXDatePicker();
        expDate = new org.jdesktop.swingx.JXDatePicker();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/give.png"))); // NOI18N
        jLabel1.setText("Distribution Event Panel");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 310, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/ngo.png"))); // NOI18N
        jLabel2.setText("Organization:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 140, 50));

        tblItems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItems);
        if (tblItems.getColumnModel().getColumnCount() > 0) {
            tblItems.getColumnModel().getColumn(0).setResizable(false);
            tblItems.getColumnModel().getColumn(1).setResizable(false);
            tblItems.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 730, 380, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/calen.png"))); // NOI18N
        jLabel4.setText("Date:");
        jLabel4.setFocusable(false);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 120, 40));

        submitRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/submit.png"))); // NOI18N
        submitRequest.setText("Submit");
        submitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRequestActionPerformed(evt);
            }
        });
        add(submitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 840, 120, 50));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/back.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 840, 120, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/sms.png"))); // NOI18N
        jLabel3.setText("Message :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 110, 30));

        messageText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextActionPerformed(evt);
            }
        });
        add(messageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 200, -1));

        ngoNameComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngoNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ngoNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngoNameComboBoxActionPerformed(evt);
            }
        });
        add(ngoNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/num.png"))); // NOI18N
        jLabel5.setText("Quantity :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 110, 40));

        itemQtyTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQtyTxtActionPerformed(evt);
            }
        });
        add(itemQtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/cal.png"))); // NOI18N
        jLabel6.setText("Date of Expiry :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 170, 40));

        AddButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/plus.png"))); // NOI18N
        AddButton.setText("Product");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, 130, 50));

        deleteItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/delete.png"))); // NOI18N
        deleteItem.setText("Product");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });
        add(deleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, 130, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/GroceryRole/box.png"))); // NOI18N
        jLabel7.setText("Item Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 120, -1));

        itemNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameTxtActionPerformed(evt);
            }
        });
        add(itemNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 200, -1));
        add(eventDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 200, -1));
        add(expDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 200, -1));

        Background.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        Background.setText("Delete Iem");
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRequestActionPerformed
        // TODO add your handling code here:
        if (eventDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please select a valid date for event!!!");
            return;
        }
        if (messageText.getText().equals("") || messageText.getText() == null) {
            JOptionPane.showMessageDialog(null, "Message cannot be blank!!!");
            return;
        }
        if (tblItems.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "Atleast one item should be added!");
            return;
        }
        if(ngoNameComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Organization name not selected!");
            return;
        }
        GroceryDistributionEventRequest request = new GroceryDistributionEventRequest();
        Date date = eventDate.getDate();
        String message = messageText.getText();

        request.setDate(date);
        request.setMessage(message);
        request.setSender(userAccount);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof NGOAdminOrganization) {
                org = organization;
                request.setStatus("Pending with Grocery Admin");
                break;
            } else if (organization instanceof GroceryAdminOrganization) {
                org = organization;
                request.setStatus("Pending with NGO Admin");
                break;
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Grocery Distribution Request created successfully!.!");
        itemNameTxt.setText("");
        messageText.setText("");
        itemQtyTxt.setText("");

    }//GEN-LAST:event_submitRequestActionPerformed

    public void populateOrganizationComboBox() {
        ngoNameComboBox.removeAllItems();
        for (Network network : business.getNetworkList()) {
            for (Enterprise enter : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enter.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                        if (ua.equals(userAccount)) {
                            if (ua.getRole() instanceof GroceryRole) {
                                for (Enterprise enter1 : network.getEnterpriseDirectory().getEnterpriseList()) {
                                    for (Organization org : enter1.getOrganizationDirectory().getOrganizationList()) {
                                        if (org instanceof NGOAdminOrganization) {
                                            ngoNameComboBox.addItem(enter1.getName());
                                        }
                                    }
                                }
                            } else if (ua.getRole() instanceof NGORole) {
                                for (Enterprise enter1 : network.getEnterpriseDirectory().getEnterpriseList()) {
                                    for (Organization org : enter1.getOrganizationDirectory().getOrganizationList()) {
                                        if (org instanceof GroceryAdminOrganization) {
                                            ngoNameComboBox.addItem(enter1.getName());
                                        }

                                    }
                                }

                            }
                        }
                    }
                }
            }
        }
    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = userProcessContainer.getComponents();
        for(Component c : comps){
            if (c instanceof NGOWorkAreaJPanel){
                NGOWorkAreaJPanel ngoPanel = (NGOWorkAreaJPanel) c;
                ngoPanel.populateTable();
            } else if (c instanceof GroceryStoreWorkAreaJPanel){
                GroceryStoreWorkAreaJPanel panel = (GroceryStoreWorkAreaJPanel) c;
                panel.populateTable();
            }   
        }
    }//GEN-LAST:event_backJButtonActionPerformed

    private void messageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextActionPerformed

    private void itemQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQtyTxtActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here
        if (itemNameTxt.getText() == null || itemNameTxt.getText().equals("") || itemQtyTxt.getText().equals("") || itemQtyTxt.getText() == null
                || expDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "One or more fields Invalid!!!");
            return;
        }
        if (expDate.getDate().getTime() < eventDate.getDate().getTime()) {
            JOptionPane.showMessageDialog(null, "Product expiry date should be atleast a month after event date!");
            return;
        }
        if (!itemQtyTxt.getText().matches("[0-9]{1,5}")){
            JOptionPane.showMessageDialog(null, "Item quantity should be numeric!");
            return;
        }
        if (!itemNameTxt.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(null, "Item name cannot be numeric!");
            return;
        }
        String iName = itemNameTxt.getText();
        int qty = Integer.parseInt(itemQtyTxt.getText());
        Date date = expDate.getDate();
        Items items = new Items();
        items.setItemName(iName);
        items.setQty(qty);
        items.setExpDate(date);
        itemList.add(items);
        populateTable(itemList);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void itemNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameTxtActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        // TODO add your handling code here:
        List<Items> newList = new ArrayList(itemList);
        int selectedRow = tblItems.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                Items item = (Items) tblItems.getValueAt(selectedRow, 0);
                itemList.remove(item);
                newList = itemList;
                populateTable(newList);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!!");
        }
    }//GEN-LAST:event_deleteItemActionPerformed

    private void ngoNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngoNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngoNameComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteItem;
    private org.jdesktop.swingx.JXDatePicker eventDate;
    private org.jdesktop.swingx.JXDatePicker expDate;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JTextField itemQtyTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageText;
    private javax.swing.JComboBox ngoNameComboBox;
    private javax.swing.JButton submitRequest;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables

    private void populateTable(List<Items> itemList) {
        DefaultTableModel model = (DefaultTableModel) tblItems.getModel();
        model.setRowCount(0);
        for (Items item : itemList) {
            Object[] row = new Object[3];
            row[0] = item;
            row[1] = item.getQty();
            row[2] = item.getExpDate();
            model.addRow(row);
        }
    }
}
