/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HrRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HrOrganization;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.NGORole.CreateWorkshopJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Hardik
 */
public class EducationalEventDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EducationalEventDashboardJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private NGOAdminOrganization ngoOrganization;
    private HrOrganization hrOrganization;
    private Enterprise enterprise;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public EducationalEventDashboardJPanel(JPanel userProcessContainer, UserAccount account, 
            HrOrganization hrOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.hrOrganization = hrOrganization;
        this.enterprise = enterprise;
        this.business = business;
        
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        String status;
        model.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(organization instanceof NGOAdminOrganization || organization instanceof HrOrganization ){
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request instanceof EducationEventWorkRequest){  
                                EducationEventWorkRequest req = (EducationEventWorkRequest) request;
                                Object[] row = new Object[2];
                                row[0] = req;
                                row[1] = req.getNgoName();
                                model.addRow(row);
                                
                            }
                        }
                    }
                }
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        detailsJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewApprovedJButton = new javax.swing.JButton();
        viewParticipatingJButton = new javax.swing.JButton();
        createEducationalWorkshopJButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Workshop Name", "NGO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(230, 360, 650, 132);

        detailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/details.png"))); // NOI18N
        detailsJButton.setText("Details");
        detailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        detailsJButton.setBorderPainted(false);
        detailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsJButtonActionPerformed(evt);
            }
        });
        add(detailsJButton);
        detailsJButton.setBounds(750, 550, 120, 50);

        refreshJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/refresh.png"))); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refreshJButton.setBorderPainted(false);
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton);
        refreshJButton.setBounds(620, 550, 120, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/workshop.png"))); // NOI18N
        jLabel1.setText("Workshop Dashboard");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1);
        jLabel1.setBounds(400, 220, 260, 80);

        viewApprovedJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/approved.png"))); // NOI18N
        viewApprovedJButton.setText("Approved");
        viewApprovedJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewApprovedJButton.setBorderPainted(false);
        viewApprovedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewApprovedJButtonActionPerformed(evt);
            }
        });
        add(viewApprovedJButton);
        viewApprovedJButton.setBounds(490, 550, 120, 50);

        viewParticipatingJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/parti.png"))); // NOI18N
        viewParticipatingJButton.setText("Participating");
        viewParticipatingJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewParticipatingJButton.setBorderPainted(false);
        viewParticipatingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewParticipatingJButtonActionPerformed(evt);
            }
        });
        add(viewParticipatingJButton);
        viewParticipatingJButton.setBounds(360, 550, 120, 50);

        createEducationalWorkshopJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createEducationalWorkshopJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/submit.png"))); // NOI18N
        createEducationalWorkshopJButton.setText("Create");
        createEducationalWorkshopJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createEducationalWorkshopJButton.setBorderPainted(false);
        createEducationalWorkshopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEducationalWorkshopJButtonActionPerformed(evt);
            }
        });
        add(createEducationalWorkshopJButton);
        createEducationalWorkshopJButton.setBounds(230, 550, 120, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background);
        Background.setBounds(-100, -50, 1260, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void detailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);

//        request.setStatus("Processing");

        PlanningEventJPanel viewWorkRequestJPanel = new PlanningEventJPanel(userProcessContainer, request, userAccount, enterprise);
        userProcessContainer.add("viewWorkRequestJPanel", viewWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_detailsJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewApprovedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewApprovedJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)workRequestJTable.getValueAt(selectedRow, 0);

//        request.setStatus("Processing");

        ViewEmployeeApprovalStatusJPanel viewApprovedEmployeesJPanel = new ViewEmployeeApprovalStatusJPanel(userProcessContainer, request, userAccount, enterprise);
        userProcessContainer.add("viewWorkRequestJPanel", viewApprovedEmployeesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewApprovedJButtonActionPerformed

    private void viewParticipatingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewParticipatingJButtonActionPerformed
        ViewParticipatingEmployeesJPanel viewParticipatedEmployeesJPanel = new ViewParticipatingEmployeesJPanel(userProcessContainer, business);
        userProcessContainer.add("viewParticipatedEmployeesJPanel", viewParticipatedEmployeesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewParticipatingJButtonActionPerformed

    private void createEducationalWorkshopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEducationalWorkshopJButtonActionPerformed
        CreateWorkshopJPanel createEducationWorkshopJPanel = new CreateWorkshopJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("createEducationWorkshopJPanel", createEducationWorkshopJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createEducationalWorkshopJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton createEducationalWorkshopJButton;
    private javax.swing.JButton detailsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewApprovedJButton;
    private javax.swing.JButton viewParticipatingJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
