/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HrRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Hardik
 */
public class PlanningEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlanningEventJPanel
     */
    JPanel userProcessContainer;
    EducationEventWorkRequest request;
    UserAccount account;
    Enterprise enterprise;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public PlanningEventJPanel(JPanel userProcessContainer, EducationEventWorkRequest request, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account=account;
        this.enterprise = enterprise;
        ngoTextBox.setText(request.getNgoName());
        workshopTextBox.setText(request.getWorkshopName());
        instructorsRequiredTextBox.setText(request.getInstructorRequired());
        dateTextBox.setText(request.getDate());
        venueTextBox.setText(request.getVenue());
        subjectTextBox.setText(request.getTopics());
        durationTextBox.setText(request.getDuration());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngoTextBox = new javax.swing.JTextField();
        instructorsRequiredTextBox = new javax.swing.JTextField();
        dateTextBox = new javax.swing.JTextField();
        venueTextBox = new javax.swing.JTextField();
        subjectTextBox = new javax.swing.JTextField();
        durationTextBox = new javax.swing.JTextField();
        commentsTextBox = new javax.swing.JTextField();
        notifyJButton = new javax.swing.JButton();
        workshopTextBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/details.png"))); // NOI18N
        jLabel1.setText("Workshop Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1);
        jLabel1.setBounds(440, 170, 210, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO Name:");
        add(jLabel2);
        jLabel2.setBounds(320, 270, 121, 45);

        ngoTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(ngoTextBox);
        ngoTextBox.setBounds(540, 330, 268, 30);

        instructorsRequiredTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructorsRequiredTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorsRequiredTextBoxActionPerformed(evt);
            }
        });
        add(instructorsRequiredTextBox);
        instructorsRequiredTextBox.setBounds(540, 370, 266, 30);

        dateTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(dateTextBox);
        dateTextBox.setBounds(540, 420, 268, 30);

        venueTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(venueTextBox);
        venueTextBox.setBounds(540, 470, 268, 30);

        subjectTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTextBoxActionPerformed(evt);
            }
        });
        add(subjectTextBox);
        subjectTextBox.setBounds(540, 510, 268, 30);

        durationTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(durationTextBox);
        durationTextBox.setBounds(540, 560, 268, 30);

        commentsTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentsTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsTextBoxActionPerformed(evt);
            }
        });
        add(commentsTextBox);
        commentsTextBox.setBounds(540, 610, 268, 30);

        notifyJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HrRole/noti.png"))); // NOI18N
        notifyJButton.setText("Notify");
        notifyJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        notifyJButton.setBorderPainted(false);
        notifyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyJButtonActionPerformed(evt);
            }
        });
        add(notifyJButton);
        notifyJButton.setBounds(690, 670, 120, 50);

        workshopTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(workshopTextBox);
        workshopTextBox.setBounds(540, 280, 268, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/work.png"))); // NOI18N
        jLabel10.setText("Workshop Name:");
        add(jLabel10);
        jLabel10.setBounds(320, 320, 150, 40);

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/back.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(550, 670, 120, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel11.setText("Date of Event :");
        add(jLabel11);
        jLabel11.setBounds(320, 410, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/teaching.png"))); // NOI18N
        jLabel3.setText("Instructors required :");
        add(jLabel3);
        jLabel3.setBounds(320, 360, 180, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel4.setText("Venue :");
        add(jLabel4);
        jLabel4.setBounds(320, 460, 90, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/topics.png"))); // NOI18N
        jLabel12.setText("Topics :");
        add(jLabel12);
        jLabel12.setBounds(320, 510, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel6.setText("Duration :");
        add(jLabel6);
        jLabel6.setBounds(320, 560, 110, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/hospital/comments.png"))); // NOI18N
        jLabel8.setText("Comments :");
        add(jLabel8);
        jLabel8.setBounds(330, 610, 116, 36);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background);
        Background.setBounds(-80, -80, 1260, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void commentsTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentsTextBoxActionPerformed

    private void notifyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyJButtonActionPerformed
        
        request.setComments(commentsTextBox.getText());
//        request.setReceiver(account);
        request.setStatus("Processing");
        request.getEnterpriseList().add(enterprise.getName());
        JOptionPane.showMessageDialog(null, "Employees Notified");
        ngoTextBox.setText("");
        instructorsRequiredTextBox.setText("");
        dateTextBox.setText("");
        venueTextBox.setText("");
        subjectTextBox.setText("");
        durationTextBox.setText("");
        workshopTextBox.setText("");
        commentsTextBox.setText("");
//        
    }//GEN-LAST:event_notifyJButtonActionPerformed

    private void instructorsRequiredTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorsRequiredTextBoxActionPerformed
        
            // TODO add your handling code here:
    }//GEN-LAST:event_instructorsRequiredTextBoxActionPerformed

    private void subjectTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTextBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
//        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
//        //sysAdminwjp.populateTree();
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);

userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField commentsTextBox;
    private javax.swing.JTextField dateTextBox;
    private javax.swing.JTextField durationTextBox;
    private javax.swing.JTextField instructorsRequiredTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JButton notifyJButton;
    private javax.swing.JTextField subjectTextBox;
    private javax.swing.JTextField venueTextBox;
    private javax.swing.JTextField workshopTextBox;
    // End of variables declaration//GEN-END:variables
}
