/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Employee.Employee;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.PrescriptionDetailsWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hardik
 */
public class CreatePrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePrescriptionJPanel
     */
    private JPanel userProcessContainer;
    private HealthEventWorkRequest request;
    private DoctorOrganization doctorOrganization;

    public CreatePrescriptionJPanel(JPanel userProcessContainer, HealthEventWorkRequest request, Organization doctorOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.doctorOrganization = (DoctorOrganization) doctorOrganization;
        ngoNameJTextField.setText(request.getNgoName());
        checkupCampNameJTextField.setText(request.getHealthWorkshopName());
//        datePicker.setDate(request.getDate());
    }

    private void disableRadio() {
        ngoNameJTextField.setEnabled(false);
        checkupCampNameJTextField.setEnabled(false);
        datePicker.setEnabled(false);
        childNameJTextField.setEnabled(false);
        ageJTextField.setEnabled(false);
        prescriptionJTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ngoNameJTextField = new javax.swing.JTextField();
        checkupCampNameJTextField = new javax.swing.JTextField();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        childNameJTextField = new javax.swing.JTextField();
        ageJTextField = new javax.swing.JTextField();
        prescriptionJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        backJButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ngoNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(ngoNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 304, -1));

        checkupCampNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(checkupCampNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 304, -1));

        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });
        add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 304, -1));

        childNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(childNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 304, -1));

        ageJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 304, -1));

        prescriptionJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(prescriptionJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 304, -1));

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/submit.png"))); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitJButton.setBorderPainted(false);
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 710, 110, 50));

        backJButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/back.png"))); // NOI18N
        backJButton3.setText("Back");
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.setBorderPainted(false);
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/medicine.png"))); // NOI18N
        jLabel1.setText("Create Prescription");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/details.png"))); // NOI18N
        jLabel3.setText("Checkup Details :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/cal.png"))); // NOI18N
        jLabel15.setText("Date:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/pat.png"))); // NOI18N
        jLabel4.setText("Patient :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/age.png"))); // NOI18N
        jLabel5.setText("Age :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/prx.png"))); // NOI18N
        jLabel6.setText("Prescription Details:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, -1, -1));

        Background.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 930));
    }// </editor-fold>//GEN-END:initComponents

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePickerActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = userProcessContainer.getComponents();
        for (Component c : comps) {
            if (c instanceof DoctorPrescriptionJPanel) {
                DoctorPrescriptionJPanel panel = (DoctorPrescriptionJPanel) c;
                panel.populateTable();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if (childNameJTextField.getText().equals("") || datePicker.getDate() == null || prescriptionJTextField.getText().equals("") || ageJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty");
            return;
        }
        int age;
        try {
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            String date = formatter.format(datePicker.getDate());
            PrescriptionDetailsWorkRequest presReq = new PrescriptionDetailsWorkRequest();
            presReq.setCampName(checkupCampNameJTextField.getText());
            presReq.setDate(date);
            presReq.setChildName(childNameJTextField.getText());
            presReq.setChildAge(Integer.parseInt(ageJTextField.getText()));
            presReq.setNgoName(ngoNameJTextField.getText());
            presReq.setPresDetails(prescriptionJTextField.getText());
            presReq.setStatus("Sent to Pharmacy");
            doctorOrganization.getWorkQueue().getWorkRequestList().add(presReq);
//        account.getWorkQueue().getWorkRequestList().add(presReq);

            JOptionPane.showMessageDialog(null, "Prescription Created Successfully and sent to Pharmacy");

            disableRadio();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a valid number for Age!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton3;
    private javax.swing.JTextField checkupCampNameJTextField;
    private javax.swing.JTextField childNameJTextField;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField ngoNameJTextField;
    private javax.swing.JTextField prescriptionJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
