/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HodOraganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.HodApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hardik
 */
public class DoctorEventRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorEventRegistrationJPanel
     */
    
    JPanel userProcessContainer;
    HealthEventWorkRequest request;
    UserAccount account;
    Organization organization;
    EcoSystem business;
    
    public DoctorEventRegistrationJPanel(JPanel userProcessContainer, HealthEventWorkRequest request, UserAccount account,Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.organization = organization;
        this.business = business;
        ngoTextBox.setText(request.getNgoName());
        doctorsRequiredTextBox.setText(request.getDoctorRequired());
        dateTextBox.setText(request.getDate());
        venueTextBox.setText(request.getDate());
        eventTextBox.setText(request.getDuration());
        commentsTextBox.setText(request.getComments());
        //registerEnabled();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorsRequiredTextBox = new javax.swing.JTextField();
        dateTextBox = new javax.swing.JTextField();
        eventTextBox = new javax.swing.JTextField();
        venueTextBox = new javax.swing.JTextField();
        commentsTextBox = new javax.swing.JTextField();
        Register = new javax.swing.JButton();
        ngoTextBox = new javax.swing.JTextField();
        backJButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorsRequiredTextBox.setEditable(false);
        doctorsRequiredTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doctorsRequiredTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsRequiredTextBoxActionPerformed(evt);
            }
        });
        add(doctorsRequiredTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 220, -1));

        dateTextBox.setEditable(false);
        dateTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(dateTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 220, -1));

        eventTextBox.setEditable(false);
        eventTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(eventTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 220, -1));

        venueTextBox.setEditable(false);
        venueTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(venueTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 540, 220, -1));

        commentsTextBox.setEditable(false);
        commentsTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commentsTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsTextBoxActionPerformed(evt);
            }
        });
        add(commentsTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 220, -1));

        Register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/submit.png"))); // NOI18N
        Register.setText("Register");
        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.setBorderPainted(false);
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 110, 40));

        ngoTextBox.setEditable(false);
        ngoTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(ngoTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 220, -1));

        backJButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/back.png"))); // NOI18N
        backJButton4.setText("Back");
        backJButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton4.setBorderPainted(false);
        backJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton4ActionPerformed(evt);
            }
        });
        add(backJButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/stethoscope.png"))); // NOI18N
        jLabel3.setText("Dr's. Required :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel4.setText("Event Date :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel5.setText("Venue:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/comments.png"))); // NOI18N
        jLabel7.setText("Comments :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel9.setText("Duration :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/camp.png"))); // NOI18N
        jLabel1.setText("Health Camp Checkup Schedule");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void doctorsRequiredTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsRequiredTextBoxActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsRequiredTextBoxActionPerformed

    private void commentsTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentsTextBoxActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed

        String date = dateTextBox.getText();

        HodApprovalWorkRequest managerRequest = new HodApprovalWorkRequest();

        managerRequest.setDate(date);
        managerRequest.setSender(account);
        managerRequest.setStatus("Pending with HoD");
        managerRequest.setNgoEventReq(request);
        for(Network network : business.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof HodOraganization)
                        managerRequest.setReceiver(organization.getUserAccountDirectory().getUserAccount(account.getEmployee().getManagerId()));
                }
            }
        }

        organization.getWorkQueue().getWorkRequestList().add(managerRequest);
        account.getWorkQueue().getWorkRequestList().add(managerRequest);
        
        JOptionPane.showMessageDialog(null, "Registration request sent to HoD for Approval");
        Register.setEnabled(false);
        //            System.out.println(organization.getWorkQueue().getWorkRequestList());

        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterActionPerformed

    private void backJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton4ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] comps = userProcessContainer.getComponents();
        for(Component c: comps) {
            if(c instanceof DoctorWorkAreaJPanel) {
                DoctorWorkAreaJPanel panel = (DoctorWorkAreaJPanel) c;
                panel.populateTable();
                panel.populateEventRegistrationStatusTable();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Register;
    private javax.swing.JButton backJButton4;
    private javax.swing.JTextField commentsTextBox;
    private javax.swing.JTextField dateTextBox;
    private javax.swing.JTextField doctorsRequiredTextBox;
    private javax.swing.JTextField eventTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JTextField venueTextBox;
    // End of variables declaration//GEN-END:variables
}
