/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HrOrganization;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXDatePicker;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Hardik
 */
public class CreateWorkshopJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEducationWorkshopJPanel
     */
    private JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise enterprise;
    //private EcoSystem system;

    public CreateWorkshopJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        //this.system = system;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        instructorNumberTextBox = new javax.swing.JTextField();
        venueTextBox = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        durationTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        topicsTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        workshopNameTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/workshop.png"))); // NOI18N
        jLabel1.setText("Create  Workshop");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 250, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/teaching.png"))); // NOI18N
        jLabel3.setText("Instructors required :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 180, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel4.setText("Venue :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel5.setText("Date of Event :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 140, 40));

        instructorNumberTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructorNumberTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        instructorNumberTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorNumberTextBoxActionPerformed(evt);
            }
        });
        add(instructorNumberTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 443, 214, 30));

        venueTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        venueTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(venueTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 543, 214, 30));

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/createform.png"))); // NOI18N
        submitJButton.setText("Workshop");
        submitJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitJButton.setBorderPainted(false);
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 750, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel6.setText("Duration :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 110, 40));

        durationTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        durationTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(durationTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 593, 214, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/topics.png"))); // NOI18N
        jLabel7.setText("Topics :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 90, 40));

        topicsTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topicsTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(topicsTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 643, 214, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/work.png"))); // NOI18N
        jLabel8.setText("Workshop Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 150, 40));

        workshopNameTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workshopNameTextBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        workshopNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopNameTextBoxActionPerformed(evt);
            }
        });
        add(workshopNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 214, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/deadline.png"))); // NOI18N
        jLabel9.setText("Deadline:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, 110, 40));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/back.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, 130, 50));
        add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 494, 210, 30));
        add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 690, 210, 30));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        if (workshopNameTextBox.getText().equals("") || instructorNumberTextBox.getText().equals("") || jXDatePicker1.getDate() == null || venueTextBox.getText().equals("") || topicsTextBox.getText().equals("") || durationTextBox.getText().equals("") || jXDatePicker2.getDate() == null) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty");
            return;
        }
        if(!durationTextBox.getText().matches("[0-9]{1,2}")){
            JOptionPane.showMessageDialog(null, "Duration has to be numeric!");
            return;
        }  
        int instructorNum;
        try {
            Pattern pattern = Pattern.compile(new String("^[a-zA-Z\\s]*$"));
            instructorNum = Integer.parseInt(instructorNumberTextBox.getText());
            String workshopName = workshopNameTextBox.getText();
            String instructorNumber = instructorNumberTextBox.getText();
            SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            String date = formatter.format(jXDatePicker1.getDate());
            //String date = dateTextBox.getText();
            String venue = venueTextBox.getText();
            String topics = topicsTextBox.getText();
            String duration = durationTextBox.getText();
            //String deadline = deadlineDateTextBox.getText();
            String deadline = formatter.format(jXDatePicker2.getDate());

            Matcher matcher = pattern.matcher(workshopName);
            Matcher matcher2 = pattern.matcher(venue);
            Matcher matcher3 = pattern.matcher(topics);
            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Workshop name should only contain alphabets!!");
                return;
            } else if (!matcher2.matches()) {
                JOptionPane.showMessageDialog(null, "Venue should only contain alphabets!");
                return;
            } else if (!matcher3.matches()) {
                JOptionPane.showMessageDialog(null, "Topic name should only contain alphabets!");
                return;
            }
            else if(jXDatePicker2.getDate().getTime() > jXDatePicker1.getDate().getTime())
            {
                JOptionPane.showMessageDialog(null, "Registration deadline cannot exceed Event date!");
                return;
            }
            

//        Date date1 = (Date) datePicker.getDate();
            EducationEventWorkRequest request = new EducationEventWorkRequest();
            request.setVenue(venue);
            request.setDate(date);
            request.setInstructorRequired(instructorNumber);
            request.setSender(userAccount);
            request.setStatus("Sent to Corporates");
            request.setNgoName(enterprise.getName());
            request.setDuration(duration);
            request.setTopics(topics);
            request.setWorkshopName(workshopName);
            request.setDeadline(deadline);
//        request.setEventDate(date1);

            Organization org = null;
            //Enterprise enterprise = 
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                //System.out.println("Organization used for creation is: "+organization.getName());

                if (organization instanceof NGOAdminOrganization) {
                    //System.out.println("Inside ngo loop");
                    org = organization;
                    break;
                } else if (organization instanceof HrOrganization) {
                    //.out.println("Inside hr loop");
                    org = organization;
                    break;
                }

            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                System.out.println("" + org.getWorkQueue().getWorkRequestList());

                userAccount.getWorkQueue().getWorkRequestList().add(request);
                System.out.println(userAccount.getWorkQueue().getWorkRequestList());
            }
            JOptionPane.showMessageDialog(null, "Education Workshop Created Successfully.!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Enter a valid number for Instructor Required!");
        }

        instructorNumberTextBox.setText("");
        workshopNameTextBox.setText("");
        jXDatePicker1.setDate(null);
        //dateTextBox.setText("");
        venueTextBox.setText("");
        topicsTextBox.setText("");
        durationTextBox.setText("");
        jXDatePicker2.setDate(null);
//deadlineDateTextBox.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void instructorNumberTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorNumberTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorNumberTextBoxActionPerformed

    private void workshopNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopNameTextBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] comps = this.userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof educationEventJPanel) {
                educationEventJPanel adminMain = (educationEventJPanel) comp;
                adminMain.populateTable();
            }
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField durationTextBox;
    private javax.swing.JTextField instructorNumberTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField topicsTextBox;
    private javax.swing.JTextField venueTextBox;
    private javax.swing.JTextField workshopNameTextBox;
    // End of variables declaration//GEN-END:variables
}
