/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HrRole.PlanningEventJPanel;
/**
 *
 * @author Priyank
 */
public class educationEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form educationEventJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    NGOAdminOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    
    public educationEventJPanel(JPanel userProcessContainer, UserAccount account, NGOAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)eventJTable.getModel();
        
        model.setRowCount(0);
        
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                                if(request instanceof EducationEventWorkRequest){
                                EducationEventWorkRequest req = (EducationEventWorkRequest) request;
                                Object[] row = new Object[1];
                                row[0] = req;
                                model.addRow(row);
                                }
                            }                            
                        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createEducationalWorkshopJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventJTable = new javax.swing.JTable();
        viewEducationalEventDetailsJButton = new javax.swing.JButton();
        removeEducationalEventDetailsJButton = new javax.swing.JButton();
        backJButton3 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/topics.png"))); // NOI18N
        jLabel1.setText("Education Event Management");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        createEducationalWorkshopJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createEducationalWorkshopJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/plus.png"))); // NOI18N
        createEducationalWorkshopJButton.setText("Event");
        createEducationalWorkshopJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createEducationalWorkshopJButton.setBorderPainted(false);
        createEducationalWorkshopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEducationalWorkshopJButtonActionPerformed(evt);
            }
        });
        add(createEducationalWorkshopJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 100, 50));

        eventJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eventJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Educational Workshop"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 580, 160));

        viewEducationalEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewEducationalEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/view.png"))); // NOI18N
        viewEducationalEventDetailsJButton.setText("View");
        viewEducationalEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewEducationalEventDetailsJButton.setBorderPainted(false);
        viewEducationalEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEducationalEventDetailsJButtonActionPerformed(evt);
            }
        });
        add(viewEducationalEventDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 101, 50));

        removeEducationalEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeEducationalEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/delete.png"))); // NOI18N
        removeEducationalEventDetailsJButton.setText("Event");
        removeEducationalEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeEducationalEventDetailsJButton.setBorderPainted(false);
        removeEducationalEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEducationalEventDetailsJButtonActionPerformed(evt);
            }
        });
        add(removeEducationalEventDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 110, 50));

        backJButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/back.png"))); // NOI18N
        backJButton3.setText("Back");
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.setBorderPainted(false);
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 101, 50));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createEducationalWorkshopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEducationalWorkshopJButtonActionPerformed
        CreateWorkshopJPanel createEducationWorkshopJPanel = new CreateWorkshopJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("createEducationWorkshopJPanel", createEducationWorkshopJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createEducationalWorkshopJButtonActionPerformed

    private void viewEducationalEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEducationalEventDetailsJButtonActionPerformed

        int selectedRow = eventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);
        EducationEventDetailsJPanel viewEventDetailsJPanel = new EducationEventDetailsJPanel(userProcessContainer, request, account, enterprise, business);
        userProcessContainer.add("viewEventDetailsJPanel", viewEventDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_viewEducationalEventDetailsJButtonActionPerformed

    private void removeEducationalEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEducationalEventDetailsJButtonActionPerformed
        int selectedRow = eventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }
        EducationEventWorkRequest request = (EducationEventWorkRequest)eventJTable.getValueAt(selectedRow, 0);

        Organization org = null;
        //Enterprise enterprise =
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NGOAdminOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().remove(request);
            account.getWorkQueue().getWorkRequestList().remove(request);
            for(Network network : business.getNetworkList()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        for(WorkRequest req : organization.getWorkQueue().getWorkRequestList()){
                            if(req instanceof ManagerApprovalWorkRequest){
                                ManagerApprovalWorkRequest managerReq = (ManagerApprovalWorkRequest) req;
                                if(managerReq.getNgoEventReq() == request){
                                    managerReq.setStatus("Event Cancelled");
                                }
                            }
                        }
                    }
                }
            }
            //            System.out.println(org.getWorkQueue().getWorkRequestList());
        }
        JOptionPane.showMessageDialog(null, "Education Workshop Event Cancelled. Corporates notified!");
        populateTable();
    }//GEN-LAST:event_removeEducationalEventDetailsJButtonActionPerformed

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton3;
    private javax.swing.JButton createEducationalWorkshopJButton;
    private javax.swing.JTable eventJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeEducationalEventDetailsJButton;
    private javax.swing.JButton viewEducationalEventDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
