/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.ManagerApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.HrRole.PlanningEventJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Hardik
 */
public class EducationEventDetailsJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form EducationEventDetailsJPanel
     */
    
    private JPanel userProcessContainer;
    private EducationEventWorkRequest request;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem business;
    
    public EducationEventDetailsJPanel(JPanel userProcessContainer, EducationEventWorkRequest request, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        ngoTextBox.setText(request.getNgoName());
        workshopTextBox.setText(request.getWorkshopName());
        instructorsRequiredTextBox.setText(request.getInstructorRequired());
        dateTextBox.setText(request.getDate());
        venueTextBox.setText(request.getDate());
        subjectTextBox.setText(request.getTopics());
        durationTextBox.setText(request.getDuration());
//        datePicker.setDate(request.getEventDate());
//        datePicker.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ngoTextBox = new javax.swing.JTextField();
        instructorsRequiredTextBox = new javax.swing.JTextField();
        dateTextBox = new javax.swing.JTextField();
        venueTextBox = new javax.swing.JTextField();
        subjectTextBox = new javax.swing.JTextField();
        durationTextBox = new javax.swing.JTextField();
        workshopTextBox = new javax.swing.JTextField();
        viewRegisteredJButton = new javax.swing.JButton();
        finishEventJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/reglist.png"))); // NOI18N
        jLabel1.setText("Scheduled  Workshop");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1);
        jLabel1.setBounds(510, 280, 258, 78);

        ngoTextBox.setEditable(false);
        ngoTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngoTextBoxActionPerformed(evt);
            }
        });
        add(ngoTextBox);
        ngoTextBox.setBounds(610, 390, 268, 30);

        instructorsRequiredTextBox.setEditable(false);
        instructorsRequiredTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructorsRequiredTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorsRequiredTextBoxActionPerformed(evt);
            }
        });
        add(instructorsRequiredTextBox);
        instructorsRequiredTextBox.setBounds(610, 490, 268, 30);

        dateTextBox.setEditable(false);
        dateTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(dateTextBox);
        dateTextBox.setBounds(610, 540, 268, 30);

        venueTextBox.setEditable(false);
        venueTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(venueTextBox);
        venueTextBox.setBounds(610, 590, 268, 30);

        subjectTextBox.setEditable(false);
        subjectTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subjectTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTextBoxActionPerformed(evt);
            }
        });
        add(subjectTextBox);
        subjectTextBox.setBounds(610, 640, 268, 30);

        durationTextBox.setEditable(false);
        durationTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(durationTextBox);
        durationTextBox.setBounds(610, 700, 268, 30);

        workshopTextBox.setEditable(false);
        workshopTextBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workshopTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopTextBoxActionPerformed(evt);
            }
        });
        add(workshopTextBox);
        workshopTextBox.setBounds(610, 440, 268, 30);

        viewRegisteredJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewRegisteredJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/reg.png"))); // NOI18N
        viewRegisteredJButton.setText("View Registered");
        viewRegisteredJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewRegisteredJButton.setBorderPainted(false);
        viewRegisteredJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegisteredJButtonActionPerformed(evt);
            }
        });
        add(viewRegisteredJButton);
        viewRegisteredJButton.setBounds(560, 770, 150, 60);

        finishEventJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finishEventJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/finish.png"))); // NOI18N
        finishEventJButton.setText("Finished");
        finishEventJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        finishEventJButton.setBorderPainted(false);
        finishEventJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishEventJButtonActionPerformed(evt);
            }
        });
        add(finishEventJButton);
        finishEventJButton.setBounds(740, 770, 140, 60);

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/back.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(390, 770, 140, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/work.png"))); // NOI18N
        jLabel8.setText("Workshop Name:");
        add(jLabel8);
        jLabel8.setBounds(390, 440, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/teaching.png"))); // NOI18N
        jLabel3.setText("Instructors required :");
        add(jLabel3);
        jLabel3.setBounds(390, 480, 180, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel5.setText("Date of Event :");
        add(jLabel5);
        jLabel5.setBounds(390, 540, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel4.setText("Venue :");
        add(jLabel4);
        jLabel4.setBounds(390, 590, 90, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/topics.png"))); // NOI18N
        jLabel7.setText("Topics :");
        add(jLabel7);
        jLabel7.setBounds(390, 640, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel6.setText("Duration :");
        add(jLabel6);
        jLabel6.setBounds(390, 700, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PharmacyRole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO Name:");
        add(jLabel2);
        jLabel2.setBounds(390, 380, 121, 45);

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background);
        Background.setBounds(0, -30, 1280, 960);
    }// </editor-fold>//GEN-END:initComponents

    private void instructorsRequiredTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorsRequiredTextBoxActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_instructorsRequiredTextBoxActionPerformed

    private void subjectTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTextBoxActionPerformed

    private void viewRegisteredJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegisteredJButtonActionPerformed
        
        EmployeesRegisteredJPanel viewRegisteredJPanel = new EmployeesRegisteredJPanel(userProcessContainer, request, account, enterprise);
        userProcessContainer.add("viewRegisteredJPanel", viewRegisteredJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewRegisteredJButtonActionPerformed

    private void finishEventJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishEventJButtonActionPerformed
        String workName = request.getWorkshopName();
        int instructorReq = Integer.parseInt(request.getInstructorRequired());
        System.out.println("Worhshop name is: " +workName+ "and instructors are:"+instructorReq);
        
        if(request.getEmployeeList().size() < instructorReq)
        {
            JOptionPane.showMessageDialog(null, "Instructores registered are less. Please wait");
        }
        else 
        {
            for(Employee emp : request.getEmployeeList()){
                for(Network network: business.getNetworkList()){
                    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                            for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                                if(request instanceof ManagerApprovalWorkRequest){
                                    String reqName = (String)((ManagerApprovalWorkRequest) request).getNgoEventReq().getWorkshopName();
                                    if(request.getSender().getEmployee() == emp && workName.equals(reqName)){
                                        request.setStatus("Event Completed");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        
        JOptionPane.showMessageDialog(null,"Event Completed!");
        // TODO add your handling code here:
        }
    }//GEN-LAST:event_finishEventJButtonActionPerformed

    private void ngoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngoTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngoTextBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void workshopTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workshopTextBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dateTextBox;
    private javax.swing.JTextField durationTextBox;
    private javax.swing.JButton finishEventJButton;
    private javax.swing.JTextField instructorsRequiredTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JTextField subjectTextBox;
    private javax.swing.JTextField venueTextBox;
    private javax.swing.JButton viewRegisteredJButton;
    private javax.swing.JTextField workshopTextBox;
    // End of variables declaration//GEN-END:variables
}
