/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.HodApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hardik
 */
public class HealthEventDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthEventDetailsJPanel
     */
    private JPanel userProcessContainer;
    private HealthEventWorkRequest request;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem business;
    
    public HealthEventDetailsJPanel(JPanel userProcessContainer, HealthEventWorkRequest request, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        ngoTextBox.setText(request.getNgoName());
        workshopTextBox.setText(request.getHealthWorkshopName());
        instructorsRequiredTextBox.setText(request.getDoctorRequired());
        dateTextBox.setText(request.getDate());
        venueTextBox.setText(request.getDate());
        durationTextBox.setText(request.getDuration());
//        datePicker.setDate(request.getEventDate());
//        datePicker.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        venueTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        durationTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        workshopTextBox = new javax.swing.JTextField();
        ngoTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        instructorsRequiredTextBox = new javax.swing.JTextField();
        viewRegisteredJButton = new javax.swing.JButton();
        dateTextBox = new javax.swing.JTextField();
        finishEventJButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/tent.png"))); // NOI18N
        jLabel9.setText("Name :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        venueTextBox.setEditable(false);
        venueTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(venueTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 268, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/ngo.png"))); // NOI18N
        jLabel2.setText("NGO :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        backJButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/back.png"))); // NOI18N
        backJButton3.setText("Back");
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.setBorderPainted(false);
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/camp.png"))); // NOI18N
        jLabel1.setText("Health Camp Checkup Schedule");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/stethoscope.png"))); // NOI18N
        jLabel3.setText("Dr's. Required :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        durationTextBox.setEditable(false);
        durationTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(durationTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 268, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/cal.png"))); // NOI18N
        jLabel4.setText("Event Date :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/time.png"))); // NOI18N
        jLabel7.setText("Duration :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, -1));

        workshopTextBox.setEditable(false);
        workshopTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(workshopTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 268, 30));

        ngoTextBox.setEditable(false);
        ngoTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(ngoTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 268, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/venue.png"))); // NOI18N
        jLabel5.setText("Venue:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        instructorsRequiredTextBox.setEditable(false);
        instructorsRequiredTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instructorsRequiredTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorsRequiredTextBoxActionPerformed(evt);
            }
        });
        add(instructorsRequiredTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 268, 30));

        viewRegisteredJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewRegisteredJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/view.png"))); // NOI18N
        viewRegisteredJButton.setText("Registered");
        viewRegisteredJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewRegisteredJButton.setBorderPainted(false);
        viewRegisteredJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegisteredJButtonActionPerformed(evt);
            }
        });
        add(viewRegisteredJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 130, 50));

        dateTextBox.setEditable(false);
        dateTextBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(dateTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 268, 30));

        finishEventJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finishEventJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/finish.png"))); // NOI18N
        finishEventJButton.setText("Finish Event");
        finishEventJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        finishEventJButton.setBorderPainted(false);
        finishEventJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishEventJButtonActionPerformed(evt);
            }
        });
        add(finishEventJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, 130, 50));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void instructorsRequiredTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorsRequiredTextBoxActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_instructorsRequiredTextBoxActionPerformed

    private void viewRegisteredJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegisteredJButtonActionPerformed

        ViewRegisteredDoctorJPanel viewRegisteredDoctorsJPanel = new ViewRegisteredDoctorJPanel(userProcessContainer, request, account, enterprise);
        userProcessContainer.add("viewRegisteredDoctorsJPanel", viewRegisteredDoctorsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        //        request.setReceiver(account);
        //        Email email = EmailBuilder.startingBlank()
        //        .from("lollypop", "lolly.pop@pretzelfun.com")
        //        .to("C. Cane", "candycane@candyshop.org")
        //        .cc("C. Bo <chocobo@candyshop.org>")
        //        .withSubject("hey")
        //        .withPlainText("We should meet up! ;)")
        //        .buildEmail();
        //
        //        mailer.sendMail(email);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRegisteredJButtonActionPerformed

    private void finishEventJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishEventJButtonActionPerformed
        for(Employee emp : request.getDoctorList()){
            for(Network network: business.getNetworkList()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request instanceof HodApprovalWorkRequest){
                                if(request.getSender().getEmployee() == emp){
                                    request.setStatus("Event Completed");
                                }
                            }
                        }
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(null,"Event Completed!");
        // TODO add your handling code here:
    }//GEN-LAST:event_finishEventJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton3;
    private javax.swing.JTextField dateTextBox;
    private javax.swing.JTextField durationTextBox;
    private javax.swing.JButton finishEventJButton;
    private javax.swing.JTextField instructorsRequiredTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JTextField venueTextBox;
    private javax.swing.JButton viewRegisteredJButton;
    private javax.swing.JTextField workshopTextBox;
    // End of variables declaration//GEN-END:variables
}
