/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGORole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.HodApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HospitalAdminRole.PlanningHealthCheckupCampJPanel;

/**
 *
 * @author Hardik
 */
public class HealthEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthEventJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    NGOAdminOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    
    public HealthEventJPanel(JPanel userProcessContainer, UserAccount account, NGOAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        populateHealthCampTable();
    }
    
    public void populateHealthCampTable(){
        DefaultTableModel model = (DefaultTableModel)healthCheckupEventJTable.getModel();
        
        model.setRowCount(0);
        
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                                if(request instanceof HealthEventWorkRequest){
                                HealthEventWorkRequest req = (HealthEventWorkRequest) request;
                                Object[] row = new Object[1];
                                row[0] = req;
                                model.addRow(row);
                                }
                        }
                    
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton3 = new javax.swing.JButton();
        removeEducationalEventDetailsJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        healthCheckupEventJTable = new javax.swing.JTable();
        createHealthCheckupCampJButton1 = new javax.swing.JButton();
        viewHealthEventDetailsJButton = new javax.swing.JButton();
        eventRegistrationJButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/camp.png"))); // NOI18N
        jLabel1.setText("Health Checkup Camp Management");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        backJButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/back.png"))); // NOI18N
        backJButton3.setText("Back");
        backJButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backJButton3.setBorderPainted(false);
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });
        add(backJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 100, 50));

        removeEducationalEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeEducationalEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/delete.png"))); // NOI18N
        removeEducationalEventDetailsJButton.setText("Event");
        removeEducationalEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeEducationalEventDetailsJButton.setBorderPainted(false);
        removeEducationalEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEducationalEventDetailsJButtonActionPerformed(evt);
            }
        });
        add(removeEducationalEventDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 110, 50));

        healthCheckupEventJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        healthCheckupEventJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Health Checkup Camp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(healthCheckupEventJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 570, 160));

        createHealthCheckupCampJButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createHealthCheckupCampJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/plus.png"))); // NOI18N
        createHealthCheckupCampJButton1.setText("Event");
        createHealthCheckupCampJButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createHealthCheckupCampJButton1.setBorderPainted(false);
        createHealthCheckupCampJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHealthCheckupCampJButton1ActionPerformed(evt);
            }
        });
        add(createHealthCheckupCampJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 100, 50));

        viewHealthEventDetailsJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewHealthEventDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/view.png"))); // NOI18N
        viewHealthEventDetailsJButton.setText("Event");
        viewHealthEventDetailsJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewHealthEventDetailsJButton.setBorderPainted(false);
        viewHealthEventDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHealthEventDetailsJButtonActionPerformed(evt);
            }
        });
        add(viewHealthEventDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 110, 50));

        eventRegistrationJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eventRegistrationJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/NGORole/submit.png"))); // NOI18N
        eventRegistrationJButton.setText("Register");
        eventRegistrationJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eventRegistrationJButton.setBorderPainted(false);
        eventRegistrationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventRegistrationJButtonActionPerformed(evt);
            }
        });
        add(eventRegistrationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, 100, 50));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/background.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void removeEducationalEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEducationalEventDetailsJButtonActionPerformed
        int selectedRow = healthCheckupEventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }
        HealthEventWorkRequest request = (HealthEventWorkRequest)healthCheckupEventJTable.getValueAt(selectedRow, 0);

        Organization org = null;
        //Enterprise enterprise =
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NGOAdminOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().remove(request);
            account.getWorkQueue().getWorkRequestList().remove(request);
            for(Network network : business.getNetworkList()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        for(WorkRequest req : organization.getWorkQueue().getWorkRequestList()){
                            if(req instanceof HodApprovalWorkRequest){
                                HodApprovalWorkRequest hodReq = (HodApprovalWorkRequest) req;
                                if(hodReq.getNgoEventReq() == request){
                                    hodReq.setStatus("Event Cancelled");
                                }
                            }
                        }
                    }
                }
            }
            //            System.out.println(org.getWorkQueue().getWorkRequestList());
        }
        JOptionPane.showMessageDialog(null, "Education Workshop Event Cancelled. Corporates notified!");
        populateHealthCampTable();
    }//GEN-LAST:event_removeEducationalEventDetailsJButtonActionPerformed

    private void createHealthCheckupCampJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHealthCheckupCampJButton1ActionPerformed
        CreateHealthCampJPanel createHealthEventJPanel = new CreateHealthCampJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("createHealthEventJPanel", createHealthEventJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createHealthCheckupCampJButton1ActionPerformed

    private void viewHealthEventDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHealthEventDetailsJButtonActionPerformed
        int selectedRow = healthCheckupEventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        HealthEventWorkRequest request = (HealthEventWorkRequest)healthCheckupEventJTable.getValueAt(selectedRow, 0);
        HealthEventDetailsJPanel viewHealthEventDetailsJPanel = new HealthEventDetailsJPanel(userProcessContainer, request, account, enterprise, business);
        userProcessContainer.add("viewHealthEventDetailsJPanel", viewHealthEventDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewHealthEventDetailsJButtonActionPerformed

    private void eventRegistrationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventRegistrationJButtonActionPerformed
        int selectedRow = healthCheckupEventJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select row from table");
            return;
        }

        HealthEventWorkRequest request = (HealthEventWorkRequest)healthCheckupEventJTable.getValueAt(selectedRow, 0);
        ViewRegisteredDoctorJPanel registeredDoctorsJPanel = new ViewRegisteredDoctorJPanel(userProcessContainer, request, account, enterprise);
        userProcessContainer.add("registeredDoctorsJPanel", registeredDoctorsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_eventRegistrationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton backJButton3;
    private javax.swing.JButton createHealthCheckupCampJButton1;
    private javax.swing.JButton eventRegistrationJButton;
    private javax.swing.JTable healthCheckupEventJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeEducationalEventDetailsJButton;
    private javax.swing.JButton viewHealthEventDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
